# Motor Vehicle Theft Analysis

## Import Libraries

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sbn
import matplotlib.pyplot as plt

## Load Datasets

In [2]:
df=pd.read_csv('locations.csv')

In [3]:
df1=pd.read_csv('make_details.csv')

In [4]:
df2=pd.read_csv('stolen_vehicles.csv')

In [5]:
# joining of tables
df3=pd.merge(df2,df,on='location_id',how='left')
df3

,vehicle_id,vehicle_type,make_id,model_year,vehicle_desc,color,date_stolen,location_id,region,country,population,density
0,1,Trailer,623.0,2021.0,BST2021D,Silver,11/5/21,102,Auckland,New Zealand,"1,695,200",343.09
1,2,Boat Trailer,623.0,2021.0,OUTBACK BOATS FT470,Silver,12/13/21,105,Gisborne,New Zealand,"52,100",6.21
2,3,Boat Trailer,623.0,2021.0,ASD JETSKI,Silver,2/13/22,102,Auckland,New Zealand,"1,695,200",343.09
3,4,Trailer,623.0,2021.0,MSC 7X4,Silver,11/13/21,106,Hawke's Bay,New Zealand,"182,700",12.92
4,5,Trailer,623.0,2018.0,D-MAX 8X5,Silver,1/10/22,102,Auckland,New Zealand,"1,695,200",343.09
...,...,...,...,...,...,...,...,...,...,...,...,...
4548,4549,NaN,NaN,NaN,NaN,NaN,2/18/22,102,Auckland,New Zealand,"1,695,200",343.09
4549,4550,NaN,NaN,NaN,NaN,NaN,2/14/22,109,Wellington,New Zealand,"543,500",67.52
4550,4551,NaN,NaN,NaN,NaN,NaN,3/9/22,102,Auckland,New Zealand,"1,695,200",343.09
4551,4552,NaN,NaN,NaN,NaN,NaN,3/7/22,109,Wellington,New Zealand,"543,500",67.52
4552,4553,NaN,NaN,NaN,NaN,NaN,3/14/22,102,Auckland,New Zealand,"1,695,200",343.09

In [6]:
df4=pd.merge(df3,df1,on='make_id',how='left').copy()

In [7]:
df4.sample(10)

,vehicle_id,vehicle_type,make_id,model_year,vehicle_desc,color,date_stolen,location_id,region,country,population,density,make_name,make_type
736,737,Utility,619.0,2001.0,HILUX,Silver,12/22/21,104,Bay of Plenty,New Zealand,"347,700",28.80,Toyota,Standard
1941,1942,Saloon,580.0,1997.0,GALANT,Silver,1/23/22,102,Auckland,New Zealand,"1,695,200",343.09,Mitsubishi,Standard
4146,4147,Stationwagon,611.0,2021.0,JIMNY,Green,1/21/22,103,Waikato,New Zealand,"513,800",21.50,Suzuki,Standard
1090,1091,Saloon,619.0,1994.0,CHASER,Green,3/29/22,104,Bay of Plenty,New Zealand,"347,700",28.80,Toyota,Standard
816,817,Stationwagon,619.0,1997.0,HILUX,Red,11/17/21,109,Wellington,New Zealand,"543,500",67.52,Toyota,Standard
1493,1494,Utility,548.0,2005.0,RODEO 4X2,White,11/25/21,102,Auckland,New Zealand,"1,695,200",343.09,Holden,Standard
3970,3971,Hatchback,578.0,2021.0,3,Yellow,1/16/22,102,Auckland,New Zealand,"1,695,200",343.09,MG,Standard
769,770,Light Van,619.0,1996.0,HIACE,White,11/4/21,104,Bay of Plenty,New Zealand,"347,700",28.80,Toyota,Standard
670,671,Moped,538.0,2014.0,SHENKE,Black,11/16/21,114,Canterbury,New Zealand,"655,000",14.72,Factory Built,Standard
2214,2215,Saloon,548.0,2010.0,CRUZE,Blue,1/15/22,102,Auckland,New Zealand,"1,695,200",343.09,Holden,Standard

In [8]:
df4.describe(include='all')

,vehicle_id,vehicle_type,make_id,model_year,vehicle_desc,color,date_stolen,location_id,region,country,population,density,make_name,make_type
count,4553.000000,4527,4538.000000,4538.00000,4520,4538,4553,4553.000000,4553,4553,4553,4553.000000,4538,4538
unique,NaN,25,NaN,NaN,1177,14,182,NaN,13,1,13,NaN,138,2
top,NaN,Stationwagon,NaN,NaN,HILUX,Silver,4/4/22,NaN,Auckland,New Zealand,"1,695,200",NaN,Toyota,Standard
freq,NaN,945,NaN,NaN,137,1272,83,NaN,1638,4553,1638,NaN,716,4348
mean,2277.000000,NaN,584.128471,2005.23182,NaN,NaN,NaN,105.779925,NaN,NaN,NaN,141.373949,NaN,NaN
std,1314.482217,NaN,35.062695,9.11763,NaN,NaN,NaN,4.686655,NaN,NaN,NaN,152.664803,NaN,NaN
min,1.000000,NaN,501.000000,1940.00000,NaN,NaN,NaN,101.000000,NaN,NaN,NaN,3.280000,NaN,NaN
25%,1139.000000,NaN,550.000000,2000.00000,NaN,NaN,NaN,102.000000,NaN,NaN,NaN,14.720000,NaN,NaN
50%,2277.000000,NaN,587.000000,2005.00000,NaN,NaN,NaN,104.000000,NaN,NaN,NaN,28.800000,NaN,NaN
75%,3415.000000,NaN,619.000000,2011.00000,NaN,NaN,NaN,109.000000,NaN,NaN,NaN,343.090000,NaN,NaN
max,4553.000000,NaN,638.000000,2022.00000,NaN,NaN,NaN,116.000000,NaN,NaN,NaN,343.090000,NaN,NaN

In [9]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4553 entries, 0 to 4552
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   vehicle_id    4553 non-null   int64
 1   vehicle_type  4527 non-null   object
 2   make_id       4538 non-null   float64
 3   model_year    4538 non-null   float64
 4   vehicle_desc  4520 non-null   object
 5   color         4538 non-null   object
 6   date_stolen   4553 non-null   object
 7   location_id   4553 non-null   int64
 8   region        4553 non-null   object
 9   country       4553 non-null   object
 10  population    4553 non-null   object
 11  density       4553 non-null   float64
 12  make_name     4538 non-null   object
 13  make_type     4538 non-null   object
dtypes: float64(3), int64(2), object(9)
memory usage: 498.1+ KB

## Data cleaning

In [10]:
# Drop the rows where non null values are less than 8.
df4=df4.dropna(thresh=8)

In [11]:
# checking for null values
df4.isnull().sum()

vehicle_id       0
vehicle_type    11
make_id          0
model_year       0
vehicle_desc    18
color            0
date_stolen      0
location_id      0
region           0
country          0
population       0
density          0
make_name        0
make_type        0
dtype: int64

In [12]:
df4['vehicle_type'].unique()

array(['Trailer', 'Boat Trailer', 'Roadbike', 'Moped', 'Trailer - Heavy',
       'Caravan', 'Hatchback', 'Saloon', 'Stationwagon', 'Tractor',
       'Trail Bike', 'Light Van', 'All Terrain Vehicle', 'Utility',
       'Other Truck', 'Sports Car', 'Flat Deck Truck', 'Light Bus',
       'Mobile Home - Light', 'Convertible', 'Heavy Van',
       'Special Purpose Vehicle', 'Articulated Truck',
       'Cab and Chassis Only', 'Mobile Machine', nan], dtype=object)

In [13]:
x=df4['vehicle_type'].mode()
x

0    Stationwagon
Name: vehicle_type, dtype: object

In [14]:
# Assigning missing values in the Vehicle_type column with the mode of vehicle_type
df4['vehicle_type']=df4['vehicle_type'].fillna('Stationwagon')

In [15]:
df4.isnull().mean()*100

vehicle_id      0.000000
vehicle_type    0.000000
make_id         0.000000
model_year      0.000000
vehicle_desc    0.396651
color           0.000000
date_stolen     0.000000
location_id     0.000000
region          0.000000
country         0.000000
population      0.000000
density         0.000000
make_name       0.000000
make_type       0.000000
dtype: float64

In [16]:
# Assigning missing values in the Vehicle_desc column with the "unknown" word.
df4['vehicle_desc']=df4['vehicle_desc'].fillna('Unknown')

In [17]:
df4.isnull().sum()

vehicle_id      0
vehicle_type    0
make_id         0
model_year      0
vehicle_desc    0
color           0
date_stolen     0
location_id     0
region          0
country         0
population      0
density         0
make_name       0
make_type       0
dtype: int64

In [18]:
# Drop the country column
df4.drop('country',axis=1,inplace=True)

In [19]:
df4.shape

(4538, 13)

In [20]:
# Converting the data type of Data_stolen column to 'datetime'.
df4['date_stolen']=pd.to_datetime(df4['date_stolen'])

C:\Users\Admin\AppData\Local\Temp\ipykernel_16584\153667214.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df4['date_stolen']=pd.to_datetime(df4['date_stolen'])

In [21]:
# Create a new column 'month' by accessing the month from date_stolen column
df4['month']=(df4['date_stolen']).dt.month

In [22]:
#Create a new column 'year' by accessing the year from date_stolen column
df4['year']=(df4['date_stolen']).dt.year

In [23]:
# Create a new column 'week_day' by accessing the day_name from date_stolen column
df4['week_day']=(df4['date_stolen']).dt.day_name()

In [24]:
# Create a new column 'vehicle_age'
df4['vehicle_age']=2022-(df4['model_year'])

In [25]:
# Create a new column 'vehicle_age_group'
df4['vehicle_age_group'] = pd.cut(
    df4['vehicle_age'],
    bins=[0, 15, 30, 45, 60, 75, 85],
    labels=['0-15', '15-30', '30-45', '45-60', '60-75','75-85'],
    include_lowest=True
)

In [26]:
df4

,vehicle_id,vehicle_type,make_id,model_year,vehicle_desc,color,date_stolen,location_id,region,population,density,make_name,make_type,month,year,week_day,vehicle_age,vehicle_age_group
0,1,Trailer,623.0,2021.0,BST2021D,Silver,2021-11-05,102,Auckland,"1,695,200",343.09,Trailer,Standard,11,2021,Friday,1.0,0-15
1,2,Boat Trailer,623.0,2021.0,OUTBACK BOATS FT470,Silver,2021-12-13,105,Gisborne,"52,100",6.21,Trailer,Standard,12,2021,Monday,1.0,0-15
2,3,Boat Trailer,623.0,2021.0,ASD JETSKI,Silver,2022-02-13,102,Auckland,"1,695,200",343.09,Trailer,Standard,2,2022,Sunday,1.0,0-15
3,4,Trailer,623.0,2021.0,MSC 7X4,Silver,2021-11-13,106,Hawke's Bay,"182,700",12.92,Trailer,Standard,11,2021,Saturday,1.0,0-15
4,5,Trailer,623.0,2018.0,D-MAX 8X5,Silver,2022-01-10,102,Auckland,"1,695,200",343.09,Trailer,Standard,1,2022,Monday,4.0,0-15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4533,4534,Stationwagon,611.0,2007.0,JIMNY,Black,2022-01-11,115,Otago,"246,000",7.89,Suzuki,Standard,1,2022,Tuesday,15.0,0-15
4534,4535,Stationwagon,520.0,2005.0,30600,Yellow,2021-11-23,102,Auckland,"1,695,200",343.09,Caterpillar,Standard,11,2021,Tuesday,17.0,15-30
4535,4536,Stationwagon,550.0,2012.0,TRX520FW2M,Red,2021-10-07,101,Northland,"201,500",16.11,Honda,Standard,10,2021,Thursday,10.0,0-15
4536,4537,Stationwagon,611.0,2010.0,RMZ250,White,2021-11-14,104,Bay of Plenty,"347,700",28.80,Suzuki,Standard,11,2021,Sunday,12.0,0-15
4537,4538,Stationwagon,550.0,2019.0,CRF 100F,Yellow,2022-01-13,115,Otago,"246,000",7.89,Honda,Standard,1,2022,Thursday,3.0,0-15

## Connecting the Python Script to MySql

In [27]:
pip install pymysql sqlalchemy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pymysql in c:\users\admin\appdata\roaming\python\python313\site-packages (1.1.3)
Requirement already satisfied: sqlalchemy in c:\programdata\anaconda3\lib\site-packages (2.0.39)
Requirement already satisfied: greenlet!=0.4.17 in c:\programdata\anaconda3\lib\site-packages (from sqlalchemy) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\programdata\anaconda3\lib\site-packages (from sqlalchemy) (4.12.2)
Note: you may need to restart the kernel to use updated packages.

In [28]:
from sqlalchemy import create_engine

# MySQL connection
#username = "root"
#password = "root"
#host = "localhost"
#port = "3306"
#database = "Motor_vehicle_theft"

engine = create_engine(f"mysql+pymysql://root:root@localhost:3306/Motor_vehicle_theft")

# Write DataFrame to MySQL
table_name = "Vehicle_theft"   # choose any table name
df4.to_sql(table_name, engine, if_exists="replace", index=False)

C:\Users\Admin\AppData\Local\Temp\ipykernel_16584\1510088569.py:14: UserWarning: The provided table name 'Vehicle_theft' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  df4.to_sql(table_name, engine, if_exists="replace", index=False)

4538

In [29]:
# Read back sample
pd.read_sql("SELECT * FROM Vehicle_theft LIMIT 5;", engine)

,vehicle_id,vehicle_type,make_id,model_year,vehicle_desc,color,date_stolen,location_id,region,population,density,make_name,make_type,month,year,week_day,vehicle_age,vehicle_age_group
0,1,Trailer,623.0,2021.0,BST2021D,Silver,2021-11-05,102,Auckland,"1,695,200",343.09,Trailer,Standard,11,2021,Friday,1.0,0-15
1,2,Boat Trailer,623.0,2021.0,OUTBACK BOATS FT470,Silver,2021-12-13,105,Gisborne,"52,100",6.21,Trailer,Standard,12,2021,Monday,1.0,0-15
2,3,Boat Trailer,623.0,2021.0,ASD JETSKI,Silver,2022-02-13,102,Auckland,"1,695,200",343.09,Trailer,Standard,2,2022,Sunday,1.0,0-15
3,4,Trailer,623.0,2021.0,MSC 7X4,Silver,2021-11-13,106,Hawke's Bay,"182,700",12.92,Trailer,Standard,11,2021,Saturday,1.0,0-15
4,5,Trailer,623.0,2018.0,D-MAX 8X5,Silver,2022-01-10,102,Auckland,"1,695,200",343.09,Trailer,Standard,1,2022,Monday,4.0,0-15